global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'sriharidevops2155@gmail.com'
  smtp_auth_username: 'sriharidevops2155@gmail.com'
  smtp_auth_password: 'gngvkyfjuygqsqhw'   # <-- use Gmail App Password
  smtp_require_tls: true

route:
  receiver: 'gmail-alert'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'gmail-alert'
    email_configs:
      - to: 'sriharidevops@gmail.com'
        send_resolved: true
        headers:
          subject: '[Prometheus Alert] {{ .CommonLabels.alertname }} - Severity: {{ .CommonLabels.severity }}'